# Generated by Django 2.2.6 on 2019-11-06 13:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 6, 13, 47, 6, 730613, tzinfo=utc)),
        ),
    ]
