# Generated by Django 2.2.6 on 2019-11-06 13:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191106_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
